# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb6257a97b2220f3c1b316ed6be19a5ddf2b88f6b68446cd3606d2528f73fd303f2c10694f637ee8f49e75e6af078c2d8538266907d1438d41e1e3d7bc734c0

test:
  secret_key_base: b229004dbbcd253a49a9cf467442d8b917de5f28f359779c8a8598c15a58f59f281871a29aca13ba3de390883ee68d750b8ea1e2a28bd130ffe25a824974dbad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
